#database creating scripts
CREATE TABLE PERSON(
	ID		INT 	PRIMARY KEY 	not null,
	FIRSTNAME	CHAR(50) 		not null,
	LASTNAME 	CHAR(70) 		not null,
	BIRTHDAY	DATE			not null,
	NATIONALID 	INT,
	LIVINGPERMITID	VARCHAR(12),
	UNIVERSITYID 	VARCHAR(10)		not null,
	TITLE		INT	references title(ID),
	DEPARTMENT INT	references department(ID),
	COMMENT	VARCHAR(255)
);

CREATE TABLE TITLE(
	ID INT PRIMARY KEY not null,
	NAME CHAR(70) not null,
	COMMENT VARCHAR(255)
);
CREATE TABLE DEPARTMENT(
	ID INT PRIMARY KEY not null,
	NAME CHAR(100),
	COMMENT VARCHAR(255)
);	
CREATE TABLE ROOM(
	ID INT PRIMARY KEY not null,
	NAME CHAR(100),
 	COMMENT VARCHAR(255)
);
CREATE TABLE SLOT(
	ID INT PRIMARY KEY not null,
	TIMESLOT VARCHAR(30) not null,
	ROOMID INT references room(ID),
	COMMENT VARCHAR(255)
);
CREATE TABLE COURSE(
	ID INT PRIMARY KEY not null,
	NAME VARCHAR(130) not null,
	COURSECODE VARCHAR(30) not null,
	PERSONID INT references person(ID),
	DESCRIPTION VARCHAR(255),
	COMMENT VARCHAR(255)
);

